// Generated by CoffeeScript 1.9.0
(function() {
  main(function() {
    var b, i, _i, _len, _ref;
    b = document.getElementsByClassName("butt");
    _ref = (0, b.length);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      i = _ref[_i];
      b[i].addEventListener("click", cl);
    }
    return cl(function() {
      var el, str;
      el = this;
      if (el.innerHTML === "C") {
        return document.getElementById("input").innerHTML = "";
      } else if (el.innerHTML === "BS") {
        str = document.getElementById("input").innerHTML;
        return document.getElementById("input").innerHTML = str.slice(0, str.length - 1);
      } else if (el.innerHTML === "=") {
        return calc();
      } else {
        return document.getElementById("input").innerHTML += el.innerHTML;
      }
    });
  });

  calc(function() {
    var data, xmlhttp;
    xmlhttp = new XMLHttpRequest();
    xmlhttp.onreadystatechange = function() {
      if (xmlhttp.readyState === 4 && xmlhttp.status === 200) {
        return document.getElementById("input").innerHTML = xmlhttp.responseText;
      }
    };
    data = document.getElementById("input").innerHTML;
    xmlhttp.open("GET", "calc?s=" + encodeURIComponent(data), true);
    return xmlhttp.send();
  });

}).call(this);
